apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-termination
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./aws-termination
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m0s
  wait: true
  postBuild:
    #substitute:
      #EIM: "12345"
      #EIM: "\"12345\""
      #EIM: "\'12345\'" #✗ Kustomization reconciliation failed: var substitution failed for 'node-termination': YAMLToJSON: YAMLToJSON: yaml: line 21: did not find expected key
      #EIM: '12345'
    substituteFrom:
      - kind: ConfigMap
        name: node-term